ALTER TABLE orders ADD COLUMN IF NOT EXISTS institution_accepted TINYINT NOT NULL DEFAULT 0 COMMENT '机构接单：1是，0否';
ALTER TABLE orders ADD COLUMN IF NOT EXISTS teacher_name VARCHAR(128) NULL COMMENT '接单老师姓名';
ALTER TABLE orders ADD COLUMN IF NOT EXISTS teacher_wechat VARCHAR(64) NULL COMMENT '老师微信';
ALTER TABLE orders ADD COLUMN IF NOT EXISTS backup_teachers TEXT NULL COMMENT '备用老师数组JSON';
