ALTER TABLE orders
  ADD COLUMN author_registration_url VARCHAR(500) NULL COMMENT '作者登记表附件URL' AFTER registration_status,
  ADD COLUMN author_registration_name VARCHAR(255) NULL COMMENT '作者登记表附件原文件名' AFTER author_registration_url,
  ADD COLUMN operation_method VARCHAR(32) NULL COMMENT '操作方式：一稿一投/两稿两投/三稿三投' AFTER author_registration_name,
  ADD COLUMN backup_teacher VARCHAR(128) NULL COMMENT '备用老师' AFTER teacher_id,
  ADD COLUMN sales_contact VARCHAR(128) NULL COMMENT '对接销售' AFTER author_verify_at,
  ADD COLUMN academic_owner VARCHAR(128) NULL COMMENT '负责教务' AFTER sales_contact,
  ADD COLUMN last_teacher_update_at DATETIME NULL COMMENT '老师最近反馈时间' AFTER academic_owner,
  ADD COLUMN customer_complaint VARCHAR(16) NULL COMMENT '是否投诉：是/否' AFTER last_teacher_update_at,
  ADD COLUMN needs_supervisor VARCHAR(16) NULL COMMENT '主管关注：是/否' AFTER customer_complaint,
  ADD COLUMN emergency_status VARCHAR(32) NULL COMMENT '应急状态' AFTER needs_supervisor,
  ADD COLUMN supervisor_note TEXT NULL COMMENT '主管备注/风险说明' AFTER emergency_status,
  ADD COLUMN submitted_expected_at DATETIME NULL COMMENT 'Submitted预计产出' AFTER current_stage,
  ADD COLUMN with_editor_expected_at DATETIME NULL COMMENT 'With Editor预计产出' AFTER submitted_expected_at,
  ADD COLUMN under_review_expected_at DATETIME NULL COMMENT 'Under Review预计产出' AFTER with_editor_expected_at,
  ADD COLUMN revision_expected_at DATETIME NULL COMMENT 'Revision预计产出' AFTER under_review_expected_at,
  ADD COLUMN accepted_expected_at DATETIME NULL COMMENT 'Accepted预计产出' AFTER revision_expected_at,
  ADD COLUMN proofing_expected_at DATETIME NULL COMMENT 'Proofing预计产出' AFTER accepted_expected_at,
  ADD COLUMN online_expected_at DATETIME NULL COMMENT 'Online预计产出' AFTER proofing_expected_at,
  ADD COLUMN indexed_expected_at DATETIME NULL COMMENT 'Indexed预计产出' AFTER online_expected_at,
  ADD COLUMN revision_due_at DATETIME NULL COMMENT '返修截止时间' AFTER revision_status,
  ADD COLUMN online_at DATETIME NULL COMMENT 'Online时间' AFTER online_status,
  ADD COLUMN indexing_at DATETIME NULL COMMENT '检索时间' AFTER indexed_status;
